server:
  port: 8080
federator:
  members:
    - url: "https://server.fire.ly/R4"
    - url: "https://blaze.life.uni-leipzig.de/fhir"
    - url: "https://hapi.fhir.org/baseR4"
  resources:
    default_: 
      - url: "https://server.fire.ly/R4"
      - url: "https://blaze.life.uni-leipzig.de/fhir"
      - url: "https://hapi.fhir.org/baseR4"
    other:  
      Observation:
        - url:  "https://hapi.fhir.org/baseR4"
      Patient:
        - url: "https://hapi.fhir.org/baseR4"
        - url: "https://server.fire.ly/R4"
      Practitioner:
        - url: "https://server.fire.ly/R4"
      AuditEvent:
        - url: "https://hapi.fhir.org/baseR4"
  setup:
    url: "https://server.fire.ly/R4"
#    url: "https://hapi.fhir.org/baseR4"
