server:
  port: 8080
federator:
  members:
    - url: "https://server.fire.ly/R4"
    #- url: "https://blaze.life.uni-leipzig.de/fhir"
    - url: "https://hapi.fhir.org/baseR4"
  resources:
    default: 
      - server: "https://server.fire.ly/R4"
      #- server: "https://blaze.life.uni-leipzig.de/fhir"
      - server: "https://hapi.fhir.org/baseR4"
    other:  
      Observation:
        - server:  "https://hapi.fhir.org/baseR4"
      Patient:
        - server: "https://hapi.fhir.org/baseR4"
        - server: "https://server.fire.ly/R4"
          read: true
      Practitioner:
        - server: "https://server.fire.ly/R4"
      AuditEvent:
        - server: "https://hapi.fhir.org/baseR4"
      metadata:
        - server: "https://server.fire.ly/R4"
  setup:
    url: "https://server.fire.ly/R4"
#    url: "https://hapi.fhir.org/baseR4"
